### ISSUE TITLE
Error building logoutURI in OpenIdAuthenticationMechanism.logout()

### ISSUE THREAD

**Issue by mlarue** [eclipse-ee4j/soteria#367]
In line https://github.com/eclipse-ee4j/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/mechanisms/OpenIdAuthenticationMechanism.java#L468 `logoutURI.toString()` is called what returns something like `org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl@7de5465f`. 

Instead `logoutURI.build().toString()` should be called.

**Comment by JSurf** [comment]
Came the same issue, created a pull request for the wildfly fork of soteria:
https://github.com/wildfly-security/wildfly-elytron-ee/pull/34

Should be fixed here as well

**Comment by arjantijms** [comment]
Oops, I somehow missed that one. Thanks for reporting it.

**Comment by ThompZon** [comment]
This is still an issue and has a [pending PR](https://github.com/eclipse-ee4j/soteria/pull/385) that seem to fix the issue and not cause any new issues. Please consider merging it!
